;;; command-palette-tests.el --- Palette layout regression checks -*- lexical-binding: t; -*-
(require 'ert)
(dolist (directory (directory-files "straight/repos" t "^[^.]"))
  (when (file-directory-p directory) (add-to-list 'load-path directory)))
(add-to-list 'load-path (expand-file-name "straight/repos/vertico/extensions"))
(require 'use-package)
(load-file "command-palette.el")

(ert-deftest palette-size-tracks-parent ()
  (let ((columns 160) (rows 50))
    (cl-letf (((symbol-function 'my/palette-parent-frame) (lambda () 'parent))
              ((symbol-function 'frame-width)
               (lambda (frame) (should (eq frame 'parent)) columns))
              ((symbol-function 'frame-height)
               (lambda (frame) (should (eq frame 'parent)) rows)))
      (should (= 100 (plist-get (my/palette-size nil) :width)))
      (setq columns 60 rows 16)
      (should (= 40 (plist-get (my/palette-size nil) :width)))
      (should (= 8 (plist-get (my/palette-size nil) :height)))
      (setq columns 30)
      (should (<= (plist-get (my/palette-size nil) :width) 22)))))

(ert-deftest palette-recenters-and-stays-onscreen ()
  (should (equal (my/palette-position '(:parent-frame-width 1200 :parent-frame-height 800
                                       :posframe-width 800 :posframe-height 300))
                 '(200 . 55)))
  (should (equal (my/palette-position '(:parent-frame-width 900 :parent-frame-height 320
                                       :posframe-width 800 :posframe-height 300))
                 '(50 . 20))))

(ert-deftest palette-refresh-ignores-closed-palette ()
  (cl-letf (((symbol-function 'my/palette-active-p) (lambda (_) nil))
            ((symbol-function 'vertico--exhibit) (lambda () (ert-fail "Palette reopened"))))
    (my/palette-refresh (selected-frame))))

(ert-deftest palette-refresh-redraws-candidates ()
  (let ((redrawn nil))
    (cl-letf (((symbol-function 'my/palette-active-p) (lambda (_) (selected-window)))
              ((symbol-function 'my/palette-size) (lambda (_) '(:height 6)))
              ((symbol-function 'vertico--exhibit)
               (lambda () (should my/palette-resizing)
                 (should (= vertico-count 5)) (setq redrawn t))))
      (my/palette-refresh (selected-frame))
      (should redrawn))))

(ert-deftest palette-unchanged-frame-does-not-schedule-more-work ()
  (let ((calls 0)
        (my/palette-resize-timer nil))
    (with-current-buffer (window-buffer (selected-window))
      (let ((my/palette-last-geometry nil))
        (cl-letf (((symbol-function 'my/palette-active-p) (lambda (_) (selected-window)))
                  ((symbol-function 'run-at-time)
                   (lambda (&rest _) (cl-incf calls) nil)))
          (my/palette-window-resized (selected-frame))
          (my/palette-window-resized (selected-frame))
          (should (= calls 1)))))))

(ert-run-tests-batch-and-exit)
