;;; modal-terminal-tests.el --- Insert gate and console checks -*- lexical-binding: t; -*-
(require 'ert)
(load-file "modal-terminal.el")
(dolist (package '("ghostel" "compat"))
  (add-to-list 'load-path (expand-file-name (concat "straight/build/" package))))
(require 'ghostel)
;; Close only test-owned shells without interactive process questions.
(defun my/test-kill-console (buffer)
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (when (and (boundp 'ghostel--process) (process-live-p ghostel--process))
        (set-process-query-on-exit-flag ghostel--process nil)))
    (kill-buffer buffer)))

(ert-deftest modal-lock-insert-and-escape ()
  (with-temp-buffer
    (text-mode)
    (my/modal-edit-mode 1)
    (should-error (insert "blocked") :type 'buffer-read-only)
    (should (eq (key-binding (kbd "i")) #'my/modal-enter-insert))
    (should (eq (key-binding (kbd "`")) #'my/quake-open))
    (call-interactively (key-binding (kbd "i")))
    (insert "allowed")
    (should (eq (key-binding (kbd "`")) #'self-insert-command))
    (call-interactively (key-binding (kbd "<escape>")))
    (should-error (delete-region (point-min) (point-max)) :type 'buffer-read-only)
    (should (equal (buffer-string) "allowed"))
    (my/modal-edit-mode -1)
    (should-not buffer-read-only)))

(ert-deftest modal-respects-original-read-only ()
  (with-temp-buffer
    (setq buffer-read-only t)
    (my/modal-edit-mode 1)
    (should-error (my/modal-enter-insert) :type 'user-error)
    (my/modal-edit-mode -1)
    (should buffer-read-only)))

(ert-deftest modal-special-buffers-unaffected ()
  (with-temp-buffer
    (special-mode)
    (my/modal-enable-editor)
    (should-not my/modal-edit-mode)))

(ert-deftest quake-terminals-are-per-buffer-and-follow-file-directory ()
  (let ((a (generate-new-buffer "editor-a"))
        (b (generate-new-buffer "editor-b")) ta tb tc)
    (unwind-protect
        (progn
          (with-current-buffer a (setq buffer-file-name (expand-file-name "file.py" default-directory)))
          (with-current-buffer b (setq default-directory temporary-file-directory))
          (setq ta (my/quake-terminal a) tb (my/quake-terminal b))
          (should-not (eq ta tb))
          (should (equal (buffer-local-value 'my/quake-source-directory ta) (my/quake-directory a)))
          (should (eq ta (my/quake-terminal a)))
          ;; A moved file gets a shell in its new directory. The old shell/job lives on.
          (with-current-buffer a (setq buffer-file-name (expand-file-name "renamed.py" temporary-file-directory)))
          (setq tc (my/quake-terminal a))
          (should-not (eq ta tc))
          (should (my/quake-native-session-live-p ta))
          (should (equal (buffer-local-value 'my/quake-source-directory tc) (my/quake-directory a))))
      (dolist (buffer (list a b ta tb tc)) (my/test-kill-console buffer)))))

(ert-deftest quake-panel-animates-top-and-restores-editor ()
  (save-window-excursion
    (delete-other-windows)
    (let ((source (generate-new-buffer "quake-editor")) terminal
          (frame (selected-frame)))
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (let ((editor (selected-window)))
              (my/quake-toggle)
              (setq terminal (window-buffer (selected-window)))
              (should (eq (window-parameter (selected-window) 'window-side) 'top))
              (sleep-for 0.3)
              (should-not (frame-parameter frame 'my/quake-timer))
              (should (= (window-total-height) (my/quake-target-height frame)))
              (my/quake-toggle)
              (sleep-for 0.3)
              (should-not (frame-parameter frame 'my/quake-window))
              (should (eq (selected-window) editor))
              (should (buffer-live-p terminal))))
        (my/quake-cancel-timer frame)
        (when-let* ((window (frame-parameter frame 'my/quake-window)))
          (when (window-live-p window) (delete-window window)))
        (set-frame-parameter frame 'my/quake-window nil)
        (dolist (buffer (list source terminal)) (my/test-kill-console buffer))))))

(ert-deftest modal-desktop-does-not-persist-editing-lock ()
  (require 'desktop)
  (with-temp-buffer
    (text-mode)
    (my/modal-edit-mode 1)
    (should buffer-read-only)
    (let* ((desktop-io-file-version 208)
           (info (desktop-buffer-info (current-buffer))))
      (should-not (nth 7 info))
      (should-not (memq 'my/modal-edit-mode (nth 4 info))))
    (should buffer-read-only)))

(ert-deftest quake-visible-console-follows-new-editor ()
  (save-window-excursion
    (delete-other-windows)
    (let ((a (generate-new-buffer "follow-a"))
          (b (generate-new-buffer "follow-b")) ta tb
          (frame (selected-frame)))
      (unwind-protect
          (progn
            (switch-to-buffer a) (text-mode)
            (let ((editor (selected-window)))
              (my/quake-toggle)
              (setq ta (current-buffer))
              ;; Reverse a still-running opening animation, then reopen it.
              (my/quake-toggle)
              (my/quake-toggle)
              (sleep-for 0.3)
              (select-window editor)
              (switch-to-buffer b) (text-mode)
              (setq default-directory temporary-file-directory)
              (my/quake-follow-editor frame)
              (setq tb (window-buffer (frame-parameter frame 'my/quake-window)))
              (should-not (eq ta tb))
              (should (eq b (buffer-local-value 'my/quake-owner tb)))
              (should (equal (my/quake-directory b) (buffer-local-value 'default-directory tb)))
              (should (eq editor (selected-window)))))
        (my/quake-cancel-timer frame)
        (when-let* ((window (frame-parameter frame 'my/quake-window)))
          (when (window-live-p window) (delete-window window)))
        (set-frame-parameter frame 'my/quake-window nil)
        (dolist (buffer (list a b ta tb)) (my/test-kill-console buffer))))))

(ert-deftest modal-global-file-open-and-console-keyboard-regression ()
  (let ((file (make-temp-file "modal-keyboard-" nil ".txt" "original"))
        buffer console)
    (unwind-protect
        (save-window-excursion
          (my/global-modal-edit-mode 1)
          (find-file file)
          (setq buffer (current-buffer))
          (should my/modal-normal)
          (should-not my/modal-original-read-only)
          (execute-kbd-macro "i")
          (should-not buffer-read-only)
          (execute-kbd-macro "x")
          (should (string-prefix-p "x" (buffer-string)))
          (execute-kbd-macro (kbd "<escape>"))
          (execute-kbd-macro "`")
          (setq console (current-buffer))
          (should (derived-mode-p 'ghostel-mode))
          (should-not buffer-read-only)
          (sleep-for 0.3)
          (execute-kbd-macro (kbd "<escape>"))
          (sleep-for 0.3)
          (should (eq buffer (current-buffer)))
          (should (equal (with-temp-buffer (insert-file-contents file) (buffer-string)) "original")))
      (my/quake-cancel-timer (selected-frame))
      (my/global-modal-edit-mode -1)
      (dolist (buf (list buffer console))
        (when (buffer-live-p buf)
          (with-current-buffer buf (set-buffer-modified-p nil))
          (my/test-kill-console buf)))
      (delete-file file))))

(ert-deftest modal-mode-change-does-not-inherit-temporary-read-only ()
  (with-temp-buffer
    (text-mode)
    (my/modal-edit-mode 1)
    (fundamental-mode)
    (should-not buffer-read-only)
    (my/modal-edit-mode 1)
    (should-not my/modal-original-read-only)
    (my/modal-enter-insert)
    (insert "editable")
    (should (equal (buffer-string) "editable"))))

(ert-run-tests-batch-and-exit)
