;;; notebook-kernel-tests.el --- Real kernel integration -*- lexical-binding: t; -*-
(require 'ert)
(load-file "notebooks.el")
(defun my/nb-test-wait (predicate &optional seconds)
  (let ((deadline (+ (float-time) (or seconds 40))))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil 0.05))
    (unless (funcall predicate)
      (error "Kernel test timed out: %s; log: %s" my/nb-status
             (when (get-buffer "*Notebook kernel log*")
               (with-current-buffer "*Notebook kernel log*" (buffer-string)))))))
(ert-deftest notebook-real-cells-persist-state-save-and-interrupt ()
  (let ((file (make-temp-file "real notebook #" nil ".ipynb")) process)
    (unwind-protect
        (save-window-excursion
          (find-file file)
          (execute-kbd-macro "i")
          (insert "value = 21\nprint('héllo')")
          (execute-kbd-macro (kbd "<S-return>"))
          (setq process my/nb-process)
          (insert "value * 2")
          (execute-kbd-macro (kbd "<C-return>"))
          (my/nb-test-wait (lambda () (null my/nb-requests)))
          (should (equal my/nb-status "Idle"))
          (should (equal "héllo\n" (gethash "text" (aref (gethash "outputs" (my/nb-cell-data (car my/nb-cells))) 0))))
          (should (equal "42" (gethash "text/plain" (gethash "data" (aref (gethash "outputs" (my/nb-cell-data (cadr my/nb-cells))) 0)))))
          (my/nb-insert) (my/nb-edit)
          (insert "print('interrupt-ready', flush=True)\nwhile True:\n    pass")
          (my/nb-run)
          (my/nb-test-wait (lambda () (> (length (gethash "outputs" (my/nb-cell-data (my/nb-current)))) 0)))
          (my/notebook-interrupt)
          (my/nb-test-wait (lambda () (null my/nb-requests)) 10)
          (should (cl-find "error" (gethash "outputs" (my/nb-cell-data (my/nb-current)))
                           :key (lambda (output) (gethash "output_type" output)) :test #'equal))
          (my/nb-insert) (my/nb-edit) (insert "val")
          (let ((completion (my/nb-complete)))
            (should (member "value" (nth 2 completion))))
          (delete-region (my/nb-cell-start (my/nb-current)) (my/nb-cell-end (my/nb-current)))
          (insert "from IPython.display import display, Image\nimport base64\ndisplay(Image(data=base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9X8AAAAASUVORK5CYII=')))")
          (my/nb-run)
          (my/nb-test-wait (lambda () (null my/nb-requests)))
          (should (gethash "image/png" (gethash "data" (aref (gethash "outputs" (my/nb-cell-data (my/nb-current))) 0))))
          (save-buffer)
          (let ((python (my/nb-python)))
            (should (zerop (call-process python nil t nil "-c"
                                         "import nbformat,sys; nbformat.validate(nbformat.read(sys.argv[1],as_version=4))" file))))
          (my/nb-stop)
          (my/nb-test-wait (lambda () (not (process-live-p process))) 10))
      (when-let* ((buffer (find-buffer-visiting file)))
        (with-current-buffer buffer (set-buffer-modified-p nil) (my/nb-stop)) (kill-buffer buffer))
      (delete-file file))))
(ert-run-tests-batch-and-exit)
