;;; notebooks-tests.el --- Native notebook regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(load-file "notebooks.el")
(defmacro my/nb-test (&rest body)
  `(save-window-excursion
     (let ((file (make-temp-file "native-notebook-" nil ".ipynb")))
       (unwind-protect
           (progn (find-file file) ,@body)
         (when-let* ((buffer (find-buffer-visiting file)))
           (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))
         (delete-file file)))))
(ert-deftest notebook-native-edit-save-roundtrip ()
  (my/nb-test
   (should (derived-mode-p 'my/notebook-mode))
   (should-not my/nb-process)
   (execute-kbd-macro (kbd "RET"))
   (execute-kbd-macro "print(42)")
   (execute-kbd-macro (kbd "<escape>"))
   (should my/nb-command-mode)
   (execute-kbd-macro "b")
   (execute-kbd-macro "m")
   (execute-kbd-macro "i")
   (execute-kbd-macro "# Notes")
   (execute-kbd-macro (kbd "C-s"))
   (let ((data (with-temp-buffer (insert-file-contents file) (json-parse-buffer))))
     (should (= 4 (gethash "nbformat" data)))
     (should (equal "print(42)" (gethash "source" (aref (gethash "cells" data) 0))))
     (should (equal "# Notes" (gethash "source" (aref (gethash "cells" data) 1))))
     (should-not (gethash "outputs" (aref (gethash "cells" data) 1))))))
(ert-deftest notebook-cell-boundary-and-delete-undo ()
  (my/nb-test
   (my/nb-edit) (insert "abc")
   (goto-char (my/nb-cell-end (my/nb-current)))
   (should-error (delete-char 1) :type 'user-error)
   (my/nb-command) (execute-kbd-macro "b")
   (execute-kbd-macro "dd")
   (should (= 1 (length my/nb-cells)))
   (execute-kbd-macro "z")
   (should (= 2 (length my/nb-cells)))
   (should (equal "abc" (gethash "source" (my/nb-cell-data (car my/nb-cells)))))))
(ert-deftest notebook-execution-shortcuts ()
  (my/nb-test
   (let (executed)
     (cl-letf (((symbol-function 'my/nb-execute-cell) (lambda (cell) (push cell executed))))
       (execute-kbd-macro (kbd "<C-return>"))
       (should (= 1 (length my/nb-cells)))
       (execute-kbd-macro (kbd "<S-return>"))
       (should (= 2 (length my/nb-cells)))
       (should my/nb-edit-mode)
       (execute-kbd-macro (kbd "<M-return>"))
       (should (= 3 (length my/nb-cells)))
       (should (= 3 (length executed)))))))
(ert-deftest notebook-output-does-not-contaminate-source ()
  (my/nb-test
   (my/nb-edit) (insert "6 * 7")
   (setq my/nb-requests (list (cons 1 (my/nb-current))))
   (my/nb-event (my/nb-object "event" "execute_result" "id" 1 "content"
                              (my/nb-object "data" (my/nb-object "text/plain" "42")
                                            "metadata" (my/nb-object) "execution_count" 1)))
   (should (string-match-p "42" (overlay-get (my/nb-cell-output (my/nb-current)) 'after-string)))
   (save-buffer)
   (let ((data (with-temp-buffer (insert-file-contents file) (json-parse-buffer))))
     (should (equal "6 * 7" (gethash "source" (aref (gethash "cells" data) 0)))))
   (should-not buffer-auto-save-file-name)))
(ert-deftest notebook-explicit-python-wins ()
  (let ((my/notebook-python "/chosen/venv/python"))
    (should (equal (my/nb-python) "/chosen/venv/python"))))
(ert-deftest notebook-metadata-markdown-and-save-as ()
  (my/nb-test
   (puthash "custom" (my/nb-object "flag" :false "empty" :null) (gethash "metadata" my/nb-document))
   (my/nb-markdown) (my/nb-edit) (insert "# Title\n**bold**") (my/nb-run)
   (should (overlayp (my/nb-cell-preview (my/nb-current))))
   (should (string-match-p "Title" (overlay-get (my/nb-cell-preview (my/nb-current)) 'display)))
   (my/nb-edit) (should-not (my/nb-cell-preview (my/nb-current)))
   (let ((destination (concat file ".copy.ipynb")))
     (unwind-protect
         (progn
           (write-file destination)
           (should (derived-mode-p 'my/notebook-mode))
           (let* ((data (with-temp-buffer (insert-file-contents destination) (json-parse-buffer)))
                  (custom (gethash "custom" (gethash "metadata" data))))
             (should (eq :false (gethash "flag" custom)))
             (should (eq :null (gethash "empty" custom)))
             (should (equal "# Title\n**bold**" (gethash "source" (aref (gethash "cells" data) 0))))))
       (when-let* ((buffer (find-buffer-visiting destination)))
         (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))
       (when (file-exists-p destination) (delete-file destination))))))
(ert-deftest notebook-python-indentation-and-readonly ()
  (my/nb-test
   (my/nb-edit) (insert "if True:")
   (execute-kbd-macro (kbd "RET"))
   (should (= 4 (current-indentation)))
   (setq my/nb-original-read-only t)
   (my/nb-command)
   (should-error (my/nb-edit) :type 'user-error)
   (should-error (my/nb-insert) :type 'user-error)
   (should-error (my/nb-run) :type 'user-error)))
(ert-run-tests-batch-and-exit)
