;;; notebooks.el --- Native notebook cells and local kernels -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'json)
(require 'subr-x)
(require 'ansi-color)
(require 'python)

(defgroup my/notebooks nil "Native Jupyter notebooks." :group 'tools)
(defcustom my/notebook-python nil
  "Python with jupyter_client and ipykernel; nil discovers a venv or PATH."
  :type '(choice (const nil) file))
(defconst my/nb-bridge (expand-file-name "notebook-kernel.py"
                                      (file-name-directory (or load-file-name buffer-file-name))))
(cl-defstruct my/nb-cell data start end output header pending-clear preview)
(defvar-local my/nb-document nil)
(defvar-local my/nb-cells nil)
(defvar-local my/nb-process nil)
(defvar-local my/nb-requests nil)
(defvar-local my/nb-sequence 0)
(defvar-local my/nb-status "Stopped")
(defvar-local my/nb-command-mode nil)
(defvar-local my/nb-edit-mode nil)
(defvar-local my/nb-rendering nil)
(defvar-local my/nb-original-read-only nil)
(defvar-local my/nb-kernel "python3")
(defvar-local my/nb-deleted nil)
(defvar-local my/nb-fontify-timer nil)
(defvar-local my/nb-completion nil)
(defvar my/nb-command-map (make-sparse-keymap))
(defvar my/nb-edit-map (make-sparse-keymap))
(defvar my/nb-emulation-maps `((my/nb-command-mode . ,my/nb-command-map)
                              (my/nb-edit-mode . ,my/nb-edit-map)))

(defun my/nb-object (&rest entries)
  (let ((table (make-hash-table :test 'equal)))
    (while entries (puthash (pop entries) (pop entries) table)) table))
(defun my/nb-text (value)
  (if (stringp value) value (mapconcat #'identity value "")))
(defun my/nb-new-cell ()
  (make-my/nb-cell :data
                  (my/nb-object "cell_type" "code" "source" ""
                                "metadata" (my/nb-object) "id" (substring (md5 (format "%s%s" (float-time) (random))) 0 12)
                                "outputs" [] "execution_count" :null)))
(defun my/nb-current ()
  (or (cl-find-if (lambda (cell) (and (>= (point) (marker-position (my/nb-cell-start cell)))
                                     (<= (point) (marker-position (my/nb-cell-end cell))))) my/nb-cells)
      (cl-find-if (lambda (cell) (>= (marker-position (my/nb-cell-end cell)) (point))) my/nb-cells)
      (car (last my/nb-cells))))
(defun my/nb-sync ()
  (dolist (cell my/nb-cells)
    (when (marker-position (my/nb-cell-start cell))
      (puthash "source" (buffer-substring-no-properties (my/nb-cell-start cell) (my/nb-cell-end cell))
               (my/nb-cell-data cell)))))
(defun my/nb-fontify (&optional buffer)
  "Fontify source cells without applying Python mode to notebook structure."
  (when (buffer-live-p (or buffer (current-buffer)))
    (with-current-buffer (or buffer (current-buffer))
      (when (derived-mode-p 'my/notebook-mode)
        (let ((my/nb-rendering t) (inhibit-read-only t))
          (with-silent-modifications
            (dolist (cell my/nb-cells)
              (let* ((start (marker-position (my/nb-cell-start cell)))
                     (end (marker-position (my/nb-cell-end cell)))
                     (source (buffer-substring-no-properties start end))
                     (mode (if (equal (gethash "cell_type" (my/nb-cell-data cell)) "code")
                               'python-mode 'text-mode))
                     (highlighted
                      (with-temp-buffer
                        (insert source)
                        (let ((python-indent-guess-indent-offset nil))
                          (delay-mode-hooks (funcall mode)))
                        (font-lock-ensure)
                        (buffer-string))))
                (remove-text-properties start end '(face nil font-lock-face nil))
                (let ((pos 0))
                  (while (< pos (length highlighted))
                    (let ((next (next-single-property-change pos 'face highlighted (length highlighted))))
                      (put-text-property (+ start pos) (+ start next) 'face (get-text-property pos 'face highlighted))
                      (setq pos next))))))))))))
(defun my/nb-changed (&rest _)
  (unless my/nb-rendering
    (when (timerp my/nb-fontify-timer) (cancel-timer my/nb-fontify-timer))
    (setq my/nb-fontify-timer (run-with-idle-timer 0.25 nil #'my/nb-fontify (current-buffer)))))
(defun my/nb-indent ()
  (interactive)
  (let* ((cell (my/nb-current))
         (start (marker-position (my/nb-cell-start cell)))
         (offset (- (point) start))
         (source (buffer-substring-no-properties start (my/nb-cell-end cell))) indentation)
    (if (equal (gethash "cell_type" (my/nb-cell-data cell)) "code")
        (progn
          (with-temp-buffer
            (insert source)
            (let ((python-indent-guess-indent-offset nil)) (delay-mode-hooks (python-mode)))
            (goto-char (min (point-max) (1+ offset)))
            (setq indentation (python-indent-calculate-indentation)))
          (indent-line-to indentation))
      (indent-relative))))
(defun my/nb-complete ()
  "Complete using the idle notebook kernel, with a bounded wait."
  (when (and my/nb-edit-mode (process-live-p my/nb-process) (equal my/nb-status "Idle"))
    (let* ((cell (my/nb-current)) (start (marker-position (my/nb-cell-start cell)))
           (id (cl-incf my/nb-sequence)) (deadline (+ (float-time) 0.5)))
      (setq my/nb-completion nil)
      (my/nb-send (my/nb-object "op" "complete" "id" id
                               "code" (buffer-substring-no-properties start (my/nb-cell-end cell))
                               "cursor" (- (point) start)))
      (while (and (< (float-time) deadline) (not (equal (car my/nb-completion) id)))
        (accept-process-output my/nb-process 0.01))
      (when (equal (car my/nb-completion) id)
        (let ((content (cdr my/nb-completion)))
          (list (+ start (gethash "cursor_start" content))
                (+ start (gethash "cursor_end" content))
                (append (gethash "matches" content) nil) :exclusive 'no))))))
(defun my/nb-tab ()
  (interactive)
  (if (and (bound-and-true-p corfu-mode) (bound-and-true-p completion-in-region-mode)
           (fboundp 'my/corfu-accept-candidate))
      (my/corfu-accept-candidate)
    (unless (completion-at-point) (my/nb-indent))))
(defun my/nb-output-text (output)
  (pcase (gethash "output_type" output)
    ("stream" (ansi-color-apply (my/nb-text (gethash "text" output))))
    ("error" (ansi-color-apply (mapconcat #'identity (gethash "traceback" output) "\n")))
    (_ (let* ((data (gethash "data" output))
              (png (and data (gethash "image/png" data)))
              (plain (and data (gethash "text/plain" data))))
         (or (and png (display-graphic-p) (image-type-available-p 'png)
                  (condition-case nil
                      (propertize " " 'display (create-image (base64-decode-string (my/nb-text png))
                                                             'png t :max-width 900))
                    (error nil)))
             (and plain (my/nb-text plain))
             "[Rich output retained; no native renderer for this MIME type]")))))
(defun my/nb-preview-markdown (cell)
  "Render common Markdown formatting locally, without executing HTML or scripts."
  (when (overlayp (my/nb-cell-preview cell)) (delete-overlay (my/nb-cell-preview cell)))
  (let ((text (with-temp-buffer
                (insert (my/nb-text (gethash "source" (my/nb-cell-data cell))))
                (goto-char (point-min))
                (while (re-search-forward "^\\(#+\\) +\\(.*\\)$" nil t)
                  (let ((title (match-string 2)))
                    (replace-match (propertize title 'face '(:height 1.3 :weight bold :foreground "#75beff")) t t)))
                (goto-char (point-min))
                (while (re-search-forward "\\*\\*\\([^*\n]+\\)\\*\\*" nil t)
                  (replace-match (propertize (match-string 1) 'face 'bold) t t))
                (goto-char (point-min))
                (while (re-search-forward "`\\([^`\n]+\\)`" nil t)
                  (replace-match (propertize (match-string 1) 'face 'font-lock-constant-face) t t))
                (buffer-string))))
    (setf (my/nb-cell-preview cell) (make-overlay (my/nb-cell-start cell) (my/nb-cell-end cell)))
    (overlay-put (my/nb-cell-preview cell) 'display text)))
(defun my/nb-refresh-output (cell)
  (let* ((data (my/nb-cell-data cell))
         (text (mapconcat #'my/nb-output-text (gethash "outputs" data) "\n")))
    (overlay-put (my/nb-cell-output cell) 'after-string
                 (unless (string-empty-p text)
                   (concat (propertize "\n  OUTPUT\n" 'face 'shadow) text "\n")))
    (overlay-put (my/nb-cell-header cell) 'before-string
                 (propertize (format "\n  %s  [%s]\n" (upcase (gethash "cell_type" data))
                                     (if (cl-find cell my/nb-requests :key #'cdr) "*"
                                       (let ((n (gethash "execution_count" data)))
                                         (if (numberp n) n " "))))
                             'face '(:foreground "#75beff" :weight bold)))))
(defun my/nb-render (&optional selected)
  (let ((my/nb-rendering t) (inhibit-read-only t) (modified (buffer-modified-p)))
    (erase-buffer) (remove-overlays)
    (dolist (cell my/nb-cells)
      (setf (my/nb-cell-header cell) (make-overlay (point) (point)))
      (insert "\n")
      (setf (my/nb-cell-start cell) (copy-marker (point)))
      (insert (my/nb-text (gethash "source" (my/nb-cell-data cell))))
      (let ((end (point)))
        (insert "\n\n")
        (setf (my/nb-cell-end cell) (copy-marker end t)
              (my/nb-cell-output cell) (make-overlay end (1+ end)))))
    (dolist (cell my/nb-cells)
      (my/nb-refresh-output cell)
      (when (my/nb-cell-preview cell) (my/nb-preview-markdown cell)))
    (my/nb-fontify)
    (goto-char (my/nb-cell-start (or selected (car my/nb-cells))))
    (set-buffer-modified-p modified)))
(defun my/nb-guard (beg end)
  (unless my/nb-rendering
    (unless (and my/nb-edit-mode
                 (cl-find-if (lambda (cell) (and (>= beg (my/nb-cell-start cell))
                                                 (<= end (my/nb-cell-end cell)))) my/nb-cells))
      (user-error "Edit within a cell; use notebook commands to change cells"))))
(defun my/nb-edit ()
  (interactive)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (let ((cell (my/nb-current)))
    (when (overlayp (my/nb-cell-preview cell))
      (delete-overlay (my/nb-cell-preview cell)) (setf (my/nb-cell-preview cell) nil))
    (setq my/nb-command-mode nil my/nb-edit-mode t buffer-read-only nil cursor-type 'bar)
    (unless (and (>= (point) (my/nb-cell-start cell)) (<= (point) (my/nb-cell-end cell)))
      (goto-char (my/nb-cell-start cell)))))
(defun my/nb-command ()
  (interactive)
  (setq my/nb-command-mode t my/nb-edit-mode nil buffer-read-only t cursor-type 'box)
  (deactivate-mark))
(defun my/nb-next (&optional previous)
  (interactive)
  (let* ((n (cl-position (my/nb-current) my/nb-cells))
         (cell (nth (max 0 (min (1- (length my/nb-cells)) (+ n (if previous -1 1)))) my/nb-cells)))
    (goto-char (my/nb-cell-start cell))))
(defun my/nb-previous () (interactive) (my/nb-next t))
(defun my/nb-insert (&optional above)
  (interactive)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (my/nb-sync)
  (let* ((index (+ (cl-position (my/nb-current) my/nb-cells) (if above 0 1)))
         (cell (my/nb-new-cell)))
    (setq my/nb-cells (append (cl-subseq my/nb-cells 0 index) (list cell) (nthcdr index my/nb-cells)))
    (my/nb-render cell) (setq buffer-undo-list nil) (set-buffer-modified-p t)))
(defun my/nb-insert-above () (interactive) (my/nb-insert t))
(defun my/nb-delete ()
  (interactive)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (my/nb-sync)
  (let ((cell (my/nb-current)))
    (push (cons (cl-position cell my/nb-cells) cell) my/nb-deleted)
    (setq my/nb-cells (delq cell my/nb-cells))
    (unless my/nb-cells (setq my/nb-cells (list (my/nb-new-cell))))
    (my/nb-render) (setq buffer-undo-list nil) (set-buffer-modified-p t)))
(defun my/nb-undo-delete ()
  (interactive)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (when-let* ((entry (pop my/nb-deleted)))
    (my/nb-sync)
    (let ((n (min (car entry) (length my/nb-cells))))
      (setq my/nb-cells (append (cl-subseq my/nb-cells 0 n) (list (cdr entry)) (nthcdr n my/nb-cells))))
    (my/nb-render (cdr entry)) (setq buffer-undo-list nil) (set-buffer-modified-p t)))
(defun my/nb-cell-type (type)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (my/nb-sync)
  (let* ((cell (my/nb-current)) (data (my/nb-cell-data cell)))
    (when (overlayp (my/nb-cell-preview cell))
      (delete-overlay (my/nb-cell-preview cell)) (setf (my/nb-cell-preview cell) nil))
    (puthash "cell_type" type data)
    (if (equal type "code")
        (progn (puthash "outputs" [] data) (puthash "execution_count" :null data))
      (remhash "outputs" data) (remhash "execution_count" data))
    (my/nb-refresh-output cell) (my/nb-fontify) (set-buffer-modified-p t)))
(defun my/nb-markdown () (interactive) (my/nb-cell-type "markdown"))
(defun my/nb-code () (interactive) (my/nb-cell-type "code"))

(defun my/nb-python ()
  (or my/notebook-python
      (let* ((root (locate-dominating-file default-directory ".venv"))
             (venv (or (getenv "VIRTUAL_ENV") (and root (expand-file-name ".venv" root))))
             (exe (and venv (expand-file-name (if (eq system-type 'windows-nt) "Scripts/python.exe" "bin/python") venv))))
        (and exe (file-executable-p exe) exe))
      (executable-find (if (eq system-type 'windows-nt) "python" "python3"))
      (executable-find "python")
      (user-error "Choose a Python interpreter with my/notebook-select-python")))
(defun my/notebook-select-python (python)
  "Use any Python/venv with jupyter_client and ipykernel; no Anaconda needed."
  (interactive "fPython executable: ")
  (my/nb-stop)
  (setq-local my/notebook-python (expand-file-name python))
  (message "Notebook Python: %s" my/notebook-python))
(defun my/nb-send (object)
  (process-send-string my/nb-process (concat (json-serialize object :null-object :null :false-object :false) "\n")))
(defun my/nb-start ()
  (unless (process-live-p my/nb-process)
    (when (file-remote-p default-directory) (user-error "Local notebook kernels only"))
    (setq my/nb-status "Starting" my/nb-requests nil)
    (let ((owner (current-buffer)))
      (setq my/nb-process
            (make-process :name "notebook-kernel" :buffer nil
                          :stderr (get-buffer-create "*Notebook kernel log*")
                          :command (list (my/nb-python) "-u" my/nb-bridge "--kernel" my/nb-kernel)
                          :coding 'utf-8-unix :connection-type 'pipe :noquery t
                          :filter #'my/nb-filter
                          :sentinel (lambda (process _event)
                                      (when (and (buffer-live-p owner)
                                                 (memq (process-status process) '(exit signal)))
                                        (with-current-buffer owner
                                          (when (eq process my/nb-process)
                                            (setq my/nb-status "Stopped" my/nb-requests nil)
                                            (dolist (cell my/nb-cells) (my/nb-refresh-output cell))
                                            (force-mode-line-update)
                                            (unless (= (process-exit-status process) 0)
                                              (message "Kernel failed. See *Notebook kernel log*. Install jupyter_client and ipykernel in the selected Python."))))))))
      (process-put my/nb-process 'owner owner)
      (process-put my/nb-process 'partial ""))))
(defun my/nb-filter (process text)
  (let* ((parts (split-string (concat (process-get process 'partial) text) "\n"))
         (owner (process-get process 'owner)))
    (process-put process 'partial (car (last parts)))
    (when (buffer-live-p owner)
      (with-current-buffer owner
        (when (eq process my/nb-process)
          (dolist (line (butlast parts))
            (unless (string-empty-p line)
              (condition-case err
                  (my/nb-event (json-parse-string line :object-type 'hash-table :array-type 'array
                                                  :null-object :null :false-object :false))
                (error (message "Notebook event: %s" (error-message-string err)))))))))))
(defun my/nb-prompt-input (buffer process prompt password)
  (when (and (buffer-live-p buffer) (process-live-p process))
    (let ((value (if password (read-passwd prompt) (read-string prompt))))
      (with-current-buffer buffer
        (when (eq process my/nb-process) (my/nb-send (my/nb-object "op" "input" "value" value)))))))
(defun my/nb-event (event)
  (let* ((kind (gethash "event" event)) (id (gethash "id" event))
         (cell (cdr (assoc id my/nb-requests))) (content (gethash "content" event)))
    (pcase kind
      ("ready" (setq my/nb-status "Idle"))
      ("fatal" (my/nb-stop) (setq my/nb-status "Failed")
       (dolist (other my/nb-cells) (my/nb-refresh-output other))
       (message "Notebook: %s" (gethash "message" event)))
      ("stopped" (setq my/nb-status "Stopped"))
      ("busy" (setq my/nb-status "Running"))
      ("complete" (setq my/nb-completion (cons id content)))
      ("input" (run-at-time 0 nil #'my/nb-prompt-input (current-buffer) my/nb-process
                            (gethash "prompt" event) (eq t (gethash "password" event))))
      ("done" (setq my/nb-requests (assoc-delete-all id my/nb-requests)
                    my/nb-status (if my/nb-requests "Running" "Idle")))
      (_ (when (and cell (memq cell my/nb-cells) (equal (gethash "cell_type" (my/nb-cell-data cell)) "code"))
           (let* ((data (my/nb-cell-data cell)) (outputs (gethash "outputs" data)))
             (cond
              ((equal kind "execute_input") (puthash "execution_count" (gethash "execution_count" content) data))
              ((equal kind "clear_output")
               (if (eq t (gethash "wait" content)) (setf (my/nb-cell-pending-clear cell) t)
                 (puthash "outputs" [] data)))
              ((member kind '("stream" "display_data" "execute_result" "error" "update_display_data"))
               (when (my/nb-cell-pending-clear cell)
                 (setq outputs []) (setf (my/nb-cell-pending-clear cell) nil))
               (if (equal kind "update_display_data")
                   (let ((display-id (gethash "display_id" (gethash "transient" content))))
                     (dolist (other my/nb-cells)
                       (mapc (lambda (output)
                               (when (equal display-id (gethash "display_id" (gethash "transient" output (my/nb-object))))
                                 (puthash "data" (gethash "data" content) output)
                                 (puthash "metadata" (gethash "metadata" content) output)))
                             (gethash "outputs" (my/nb-cell-data other)))
                       (my/nb-refresh-output other)))
                 (puthash "output_type" kind content)
                 (puthash "outputs" (vconcat outputs (vector content)) data))))
             (set-buffer-modified-p t)))))
    (when (and cell (memq cell my/nb-cells)) (my/nb-refresh-output cell))
    (force-mode-line-update)))
(defun my/nb-execute-cell (cell)
  (when (equal (gethash "cell_type" (my/nb-cell-data cell)) "code")
    (my/nb-start)
    (when (cl-find cell my/nb-requests :key #'cdr) (user-error "Cell is already queued or running"))
    (let ((id (cl-incf my/nb-sequence)))
      (push (cons id cell) my/nb-requests)
      (puthash "outputs" [] (my/nb-cell-data cell))
      (setf (my/nb-cell-pending-clear cell) nil)
      (my/nb-refresh-output cell)
      (set-buffer-modified-p t)
      (my/nb-send (my/nb-object "op" "execute" "id" id "code" (gethash "source" (my/nb-cell-data cell)))))))
(defun my/nb-run ()
  (interactive)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (my/nb-sync)
  (if (equal (gethash "cell_type" (my/nb-cell-data (my/nb-current))) "markdown")
      (my/nb-preview-markdown (my/nb-current))
    (my/nb-execute-cell (my/nb-current)))
  (my/nb-command))
(defun my/nb-run-next ()
  (interactive)
  (my/nb-run)
  (if (eq (my/nb-current) (car (last my/nb-cells)))
      (progn (my/nb-insert) (my/nb-edit)) (my/nb-next)))
(defun my/nb-run-insert () (interactive) (my/nb-run) (my/nb-insert) (my/nb-edit))
(defun my/notebook-run-all ()
  (interactive)
  (when my/nb-original-read-only (user-error "Notebook file is read-only"))
  (my/nb-sync) (dolist (cell my/nb-cells) (my/nb-execute-cell cell)))
(defun my/notebook-interrupt ()
  (interactive)
  (when (process-live-p my/nb-process) (my/nb-send (my/nb-object "op" "interrupt"))))
(defun my/nb-stop ()
  (interactive)
  (when (timerp my/nb-fontify-timer) (cancel-timer my/nb-fontify-timer))
  (when (process-live-p my/nb-process)
    (my/nb-send (my/nb-object "op" "shutdown"))
    (process-send-eof my/nb-process))
  (setq my/nb-process nil my/nb-requests nil my/nb-status "Stopped"))
(defun my/notebook-restart-kernel () (interactive) (my/nb-stop) (my/nb-start))
(defun my/notebook-select-kernel ()
  (interactive)
  (let ((python (my/nb-python)) kernels)
    (with-temp-buffer
      (unless (zerop (call-process python nil t nil my/nb-bridge "--list"))
        (user-error "Cannot list kernels; install jupyter_client and ipykernel in %s" python))
      (setq kernels (json-parse-string (buffer-string) :object-type 'hash-table)))
    (let ((name (completing-read "Kernel: " (hash-table-keys kernels) nil t nil nil my/nb-kernel)))
      (when my/nb-original-read-only (user-error "Notebook file is read-only"))
      (my/nb-stop) (setq my/nb-kernel name)
      (puthash "kernelspec" (my/nb-object "name" name "display_name" (gethash name kernels))
               (gethash "metadata" my/nb-document))
      (set-buffer-modified-p t))))
(defun my/nb-save ()
  "Write notebook JSON rather than rendered editor text."
  (my/nb-sync)
  (puthash "cells" (vconcat (mapcar #'my/nb-cell-data my/nb-cells)) my/nb-document)
  (let* ((copy (json-parse-string (json-serialize my/nb-document :null-object :null :false-object :false)))
         (coding-system-for-write 'utf-8-unix))
    (mapc (lambda (cell) (mapc (lambda (output) (remhash "transient" output)) (gethash "outputs" cell)))
          (gethash "cells" copy))
    (write-region (concat (json-serialize copy :null-object :null :false-object :false) "\n")
                  nil buffer-file-name nil 'silent))
  (set-visited-file-modtime) (set-buffer-modified-p nil) t)
(defun my/notebook-open (&optional file)
  (interactive)
  (if (derived-mode-p 'my/notebook-mode) (my/nb-run)
    (find-file (or file (read-file-name "Notebook: " nil nil t)))))
(defun my/notebook-new (file)
  (interactive "FNew notebook: ")
  (unless (string-suffix-p ".ipynb" file t) (setq file (concat file ".ipynb")))
  (when (file-exists-p file) (user-error "File already exists"))
  (find-file file))

(defun my/nb-header-button (label command)
  (let ((map (make-sparse-keymap)))
    (define-key map [header-line mouse-1] command)
    (propertize label 'face 'link 'mouse-face 'highlight 'local-map map)))
(defun my/nb-header ()
  (concat (format "  %s | %s | %s  " (if my/nb-edit-mode "EDIT" "COMMAND") my/nb-kernel my/nb-status)
          (my/nb-header-button "Run" #'my/nb-run) "  "
          (my/nb-header-button "Run All" #'my/notebook-run-all) "  "
          (my/nb-header-button "Interrupt" #'my/notebook-interrupt) "  "
          (my/nb-header-button "Restart" #'my/notebook-restart-kernel) "  "
          (my/nb-header-button "Kernel" #'my/notebook-select-kernel) "  "
          (my/nb-header-button "Python" #'my/notebook-select-python)))

(defun my/nb-validate (document)
  "Reject malformed input before replacing its JSON with the cell view."
  (unless (and (hash-table-p document) (equal (gethash "nbformat" document) 4)
               (vectorp (gethash "cells" document)) (hash-table-p (gethash "metadata" document)))
    (user-error "Expected a version 4 Jupyter notebook with cells and metadata"))
  (mapc (lambda (cell)
          (unless (and (hash-table-p cell)
                       (member (gethash "cell_type" cell) '("code" "markdown" "raw"))
                       (hash-table-p (gethash "metadata" cell))
                       (let ((source (gethash "source" cell)))
                         (or (stringp source) (and (vectorp source) (cl-every #'stringp source))))
                       (or (not (equal (gethash "cell_type" cell) "code"))
                           (and (vectorp (gethash "outputs" cell))
                                (cl-every #'hash-table-p (gethash "outputs" cell)))))
            (user-error "Malformed notebook cell; original JSON has been preserved")))
        (gethash "cells" document)))

(define-derived-mode my/notebook-mode special-mode "Notebook"
  "Edit notebook cells. Enter/i edits; Esc selects command mode."
  (use-local-map (copy-keymap text-mode-map))
  (let ((raw (buffer-substring-no-properties (point-min) (point-max))))
    (setq my/nb-original-read-only (and buffer-file-name (file-exists-p buffer-file-name)
                                       (not (file-writable-p buffer-file-name))))
    (setq my/nb-document
          (if (string-empty-p raw)
              (my/nb-object "nbformat" 4 "nbformat_minor" 5 "metadata" (my/nb-object) "cells" [])
            (json-parse-string raw :object-type 'hash-table :array-type 'array :null-object :null :false-object :false)))
    (my/nb-validate my/nb-document)
    (setq my/nb-cells (mapcar (lambda (data) (make-my/nb-cell :data data)) (gethash "cells" my/nb-document)))
    (unless my/nb-cells (setq my/nb-cells (list (my/nb-new-cell))))
    (setq my/nb-kernel (or (gethash "name" (gethash "kernelspec" (gethash "metadata" my/nb-document) (my/nb-object))) "python3")))
  (setq-local my/nb-command-mode t my/nb-edit-mode nil cua-mode nil
              truncate-lines nil display-line-numbers nil global-hl-line-mode nil
              indent-line-function #'my/nb-indent
              header-line-format '(:eval (my/nb-header)))
  (setq-local emulation-mode-map-alists (cons 'my/nb-emulation-maps emulation-mode-map-alists))
  (my/nb-render)
  (when (and buffer-file-name (= (or (file-attribute-size (file-attributes buffer-file-name)) 0) 0))
    (set-buffer-modified-p t))
  (buffer-enable-undo)
  (setq buffer-undo-list nil)
  (add-hook 'before-change-functions #'my/nb-guard nil t)
  (add-hook 'after-change-functions #'my/nb-changed nil t)
  (add-hook 'write-contents-functions #'my/nb-save nil t)
  (add-hook 'kill-buffer-hook #'my/nb-stop nil t)
  (add-hook 'change-major-mode-hook #'my/nb-stop nil t)
  (setq-local completion-at-point-functions '(my/nb-complete) corfu-auto nil)
  (when (fboundp 'corfu-mode) (corfu-mode 1))
  (setq-local buffer-auto-save-file-name nil auto-save-default nil)
  (auto-save-mode -1))

(dolist (map (list my/nb-command-map my/nb-edit-map))
  (define-key map (kbd "<S-return>") #'my/nb-run-next)
  (define-key map (kbd "<C-return>") #'my/nb-run)
  (define-key map (kbd "<M-return>") #'my/nb-run-insert)
  (define-key map (kbd "<C-S-return>") #'my/notebook-run-all)
  (define-key map (kbd "<f5>") #'my/nb-run)
  (define-key map (kbd "<escape>") #'my/nb-command)
  (define-key map (kbd "C-s") #'save-buffer))
(dolist (entry '(("RET" . my/nb-edit) ("i" . my/nb-edit) ("a" . my/nb-insert-above)
                 ("b" . my/nb-insert) ("d d" . my/nb-delete) ("z" . my/nb-undo-delete)
                 ("m" . my/nb-markdown) ("y" . my/nb-code) ("j" . my/nb-next)
                 ("k" . my/nb-previous) ("<down>" . my/nb-next) ("<up>" . my/nb-previous)))
  (define-key my/nb-command-map (kbd (car entry)) (cdr entry)))
(define-key my/nb-edit-map (kbd "RET") #'newline-and-indent)
(define-key my/nb-edit-map (kbd "C-v") #'yank)
(define-key my/nb-edit-map (kbd "C-c") #'kill-ring-save)
(define-key my/nb-edit-map (kbd "C-x") #'kill-region)
(define-key my/nb-edit-map (kbd "C-z") #'undo-only)
(define-key my/nb-edit-map (kbd "TAB") #'my/nb-tab)
(define-key my/nb-edit-map (kbd "<tab>") #'my/nb-tab)
(define-key my/nb-command-map (kbd "`") #'my/quake-open)
(remove-hook 'find-file-hook #'my/notebook-setup)
(add-to-list 'auto-mode-alist '("\\.ipynb\\'" . my/notebook-mode))
(defun my/nb-shutdown-all ()
  (dolist (buffer (buffer-list))
    (with-current-buffer buffer (when (derived-mode-p 'my/notebook-mode) (my/nb-stop)))))
(add-hook 'kill-emacs-hook #'my/nb-shutdown-all)
(provide 'notebooks)
