;;; search-panel.el --- Floating live Find and Replace -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'subr-x)
(require 'wid-edit)

(cl-defstruct my/search-state source window parent panel popup find replace status
              query replacement case-sensitive regexp whole-word matches overlays
              (index 0) timer replacing origin truncated geometry)
(defvar my/search-session nil)
(defvar my/search-last-query "")
(defvar my/search-last-replacement "")
(defconst my/search-highlight-limit 2000)
(defface my/search-match '((t (:background "#614a16" :foreground "#fff0a8"))) "Search match.")
(defface my/search-current '((t (:background "#094771" :foreground "#ffffff" :box "#75beff"))) "Current match.")

(defun my/search-pattern (state)
  (let ((query (my/search-state-query state)))
    (if (string-empty-p query) nil
      (let ((pattern (if (my/search-state-regexp state) query (regexp-quote query))))
        (if (my/search-state-whole-word state) (concat "\\_<\\(?:" pattern "\\)\\_>") pattern)))))

(defun my/search-status (state text)
  (when (overlayp (my/search-state-status state))
    (overlay-put (my/search-state-status state) 'display
                 (propertize text 'face '(:foreground "#b8cce5")))))

(defun my/search-clear-highlights (state)
  (mapc #'delete-overlay (my/search-state-overlays state))
  (setf (my/search-state-overlays state) nil))

(defun my/search-reveal (state)
  (let* ((matches (my/search-state-matches state))
         (index (my/search-state-index state))
         (match (nth index matches))
         (window (my/search-state-window state)))
    (cl-loop for overlay in (my/search-state-overlays state) for n from 0 do
             (overlay-put overlay 'face (if (= n index) 'my/search-current 'my/search-match)))
    (when (and match (window-live-p window))
      (set-window-point window (car match))
      (with-selected-window window
        (goto-char (car match))
        (unless (pos-visible-in-window-p (point) window) (recenter))))
    (my/search-status state
                      (if matches
                          (format "%d of %d%s matches" (1+ index) (length matches)
                                  (if (my/search-state-truncated state) "+" ""))
                        "No matches"))))

(defun my/search-refresh (&optional state)
  "Update live matches without changing input focus."
  (setq state (or state my/search-session))
  (when (and state (buffer-live-p (my/search-state-source state)))
    (when (timerp (my/search-state-timer state)) (cancel-timer (my/search-state-timer state)))
    (setf (my/search-state-timer state) nil)
    (my/search-clear-highlights state)
    (setf (my/search-state-matches state) nil (my/search-state-truncated state) nil)
    (condition-case err
        (let ((pattern (my/search-pattern state)) matches overlays)
          (when pattern
            (with-current-buffer (my/search-state-source state)
              (save-excursion
                (goto-char (point-min))
                (let ((case-fold-search (not (my/search-state-case-sensitive state)))
                      (count 0) done)
                  (while (and (not done) (re-search-forward pattern nil t))
                    (if (>= count my/search-highlight-limit)
                        (setq done t)
                      (let ((beg (match-beginning 0)) (end (match-end 0)))
                        (push (cons beg end) matches)
                        (let ((overlay (make-overlay beg end)))
                          (overlay-put overlay 'priority 1001)
                          (overlay-put overlay 'face 'my/search-match)
                          (when (= beg end) (overlay-put overlay 'before-string
                                                         (propertize "|" 'face 'my/search-match)))
                          (push overlay overlays))
                        (cl-incf count)
                        (when (= beg end)
                          (if (eobp) (setq done t) (forward-char 1))))))
                  (setf (my/search-state-truncated state) (>= count my/search-highlight-limit))))))
          (setf (my/search-state-matches state) (nreverse matches)
                (my/search-state-overlays state) (nreverse overlays))
          (let ((origin (my/search-state-origin state)))
            (when origin
              (setf (my/search-state-index state)
                    (or (cl-position-if (lambda (match) (>= (car match) origin))
                                        (my/search-state-matches state)) 0)
                    (my/search-state-origin state) nil)))
          (setf (my/search-state-index state)
                (min (my/search-state-index state) (max 0 (1- (length (my/search-state-matches state))))))
          (if pattern (my/search-reveal state) (my/search-status state "Type to search this file")))
      (invalid-regexp (my/search-status state (error-message-string err))))))

(defun my/search-schedule (&rest _)
  (when-let* ((state my/search-session))
    (when (timerp (my/search-state-timer state)) (cancel-timer (my/search-state-timer state)))
    (setf (my/search-state-timer state) (run-at-time 0.08 nil #'my/search-refresh state))))

(defun my/search-input-changed (widget &rest _)
  (when-let* ((state my/search-session))
    (setf (my/search-state-query state) (widget-value widget)
          (my/search-state-origin state)
          (when (window-live-p (my/search-state-window state)) (window-point (my/search-state-window state))))
    (my/search-schedule)))

(defun my/search-next (&optional backward)
  (interactive)
  (when-let* ((state my/search-session))
    (my/search-refresh state)
    (when (my/search-state-matches state)
      (setf (my/search-state-index state)
            (mod (+ (my/search-state-index state) (if backward -1 1))
                 (length (my/search-state-matches state)))))
    (my/search-reveal state)))
(defun my/search-previous () (interactive) (my/search-next t))

(defun my/search-replace (&optional all)
  "Replace the current match, or all matches, as one undoable edit."
  (interactive)
  (when-let* ((state my/search-session)
              (pattern (my/search-pattern state)))
    (my/search-refresh state)
    (let ((replacement (my/search-state-replacement state)) (count 0))
      (with-current-buffer (my/search-state-source state)
        ;; Clicking Replace is an explicit edit; preserve the keyboard insert gate.
        (let ((buffer-read-only (if (bound-and-true-p my/modal-edit-mode)
                                    my/modal-original-read-only buffer-read-only))
              (case-fold-search (not (my/search-state-case-sensitive state))))
          (barf-if-buffer-read-only)
          (atomic-change-group
            (save-excursion
              (if all
                  (progn
                    (goto-char (point-min))
                    (let (done)
                      (while (and (not done) (re-search-forward pattern nil t))
                        (let ((empty (= (match-beginning 0) (match-end 0))))
                          (replace-match replacement t (not (my/search-state-regexp state)))
                          (cl-incf count)
                          (when empty (if (eobp) (setq done t) (forward-char 1)))))))
                (when-let* ((match (nth (my/search-state-index state) (my/search-state-matches state))))
                  (goto-char (car match))
                  (when (re-search-forward pattern (cdr match) t)
                    (replace-match replacement t (not (my/search-state-regexp state)))
                    (setq count 1)
                    (setf (my/search-state-origin state) (point)))))))))
      (my/search-refresh state)
      (message "Replaced %d match%s" count (if (= count 1) "" "es")))))
(defun my/search-replace-all () (interactive) (my/search-replace t))

(defun my/search-select-field ()
  (interactive)
  (when-let* ((widget (widget-field-at (point))))
    (goto-char (widget-field-start widget))
    (push-mark (widget-field-end widget) t t)))

(defvar my/search-field-map
  (let ((map (copy-keymap widget-field-keymap)))
    (define-key map (kbd "RET") #'my/search-next)
    (define-key map (kbd "<S-return>") #'my/search-previous)
    (define-key map (kbd "C-a") #'my/search-select-field)
    (define-key map (kbd "C-v") #'yank)
    (define-key map (kbd "C-c") #'kill-ring-save)
    (define-key map (kbd "C-x") #'kill-region)
    (define-key map (kbd "<escape>") #'my/search-close)
    (define-key map (kbd "C-f") #'my/search-open)
    (define-key map (kbd "C-r") #'my/search-open-replace)
    map))
(define-derived-mode my/search-panel-mode special-mode "Find / Replace"
  "Floating find and replace controls."
  (setq buffer-read-only nil truncate-lines t
        mode-line-format nil cursor-type 'bar)
  (setq-local cua-mode nil)
  (use-local-map (copy-keymap widget-keymap))
  (local-set-key (kbd "<escape>") #'my/search-close)
  (local-set-key (kbd "C-f") #'my/search-open)
  (local-set-key (kbd "C-r") #'my/search-open-replace))

(defun my/search-build-panel (state)
  (with-current-buffer (my/search-state-panel state)
    (my/search-panel-mode)
    (let ((inhibit-read-only t)) (erase-buffer) (remove-overlays))
    (setq-local face-remapping-alist
                '((default (:background "#252526" :foreground "#cccccc"))
                  (widget-field (:background "#3c3c3c" :foreground "#ffffff"))
                  (widget-button (:foreground "#75beff" :weight bold))))
    (widget-insert (if (my/search-state-replacing state) "  FIND & REPLACE\n\n" "  FIND IN FILE\n\n"))
    (widget-insert " Find:    ")
    (setf (my/search-state-find state)
          (widget-create 'editable-field :size 38 :format "%v" :keymap my/search-field-map
                         :notify #'my/search-input-changed (my/search-state-query state)))
    (widget-insert "\n\n")
    (when (my/search-state-replacing state)
      (widget-insert " Replace: ")
      (setf (my/search-state-replace state)
            (widget-create 'editable-field :size 38 :format "%v" :keymap my/search-field-map
                           :notify (lambda (widget &rest _)
                                     (setf (my/search-state-replacement state) (widget-value widget)))
                           (my/search-state-replacement state)))
      (widget-insert "\n\n"))
    (dolist (option '((case-sensitive . " Aa ") (whole-word . " Word ") (regexp . " .* ")))
      (let ((key (car option)))
        (widget-create 'checkbox
                       :value (pcase key ('case-sensitive (my/search-state-case-sensitive state))
                                ('whole-word (my/search-state-whole-word state))
                                ('regexp (my/search-state-regexp state)))
                       :notify (lambda (widget &rest _)
                                 (pcase key
                                   ('case-sensitive (setf (my/search-state-case-sensitive state) (widget-value widget)))
                                   ('whole-word (setf (my/search-state-whole-word state) (widget-value widget)))
                                   ('regexp (setf (my/search-state-regexp state) (widget-value widget))))
                                 (my/search-refresh state)))
        (widget-insert (cdr option))))
    (widget-insert "\n\n ")
    (dolist (action (append '(("Previous" . my/search-previous) ("Next" . my/search-next))
                            (when (my/search-state-replacing state)
                              '(("Replace" . my/search-replace) ("Replace All" . my/search-replace-all)))
                            '(("Close" . my/search-close))))
      (let ((command (cdr action)))
        (widget-create 'push-button :notify (lambda (&rest _) (call-interactively command)) (car action)))
      (widget-insert " "))
    (widget-insert "\n\n ")
    (let ((start (point)))
      (widget-insert " ")
      (setf (my/search-state-status state) (make-overlay start (point))))
    (widget-insert "\n Enter: next   Shift+Enter: previous   Esc: close\n")
    (widget-setup)
    (buffer-enable-undo)
    (goto-char (widget-field-start (my/search-state-find state)))))

(defun my/search-position (info)
  (cons (max 0 (- (plist-get info :parent-frame-width) (plist-get info :posframe-width) 20))
        (min 50 (max 0 (- (plist-get info :parent-frame-height) (plist-get info :posframe-height))))))

(defun my/search-show (state &optional focus)
  (let* ((parent (my/search-state-parent state))
         (buffer (my/search-state-panel state)))
    (setf (my/search-state-geometry state) (cons (frame-pixel-width parent) (frame-pixel-height parent)))
    (if (and (display-graphic-p parent) (require 'posframe nil t) (posframe-workable-p))
        (let ((popup
               (with-selected-frame parent
                 (posframe-show buffer :poshandler #'my/search-position :accept-focus t
                                :width (min 60 (max 20 (- (frame-width parent) 4)))
                                :height (if (my/search-state-replacing state) 14 12)
                                :border-width 1 :border-color "#454545"
                                :internal-border-width 10 :background-color "#252526"
                                :foreground-color "#cccccc" :cursor 'bar))))
          (setf (my/search-state-popup state) popup)
          (when focus (select-frame-set-input-focus popup)))
      (let ((window (display-buffer-in-side-window buffer '((side . top) (slot . 1) (window-height . 14)))))
        (when focus (select-window window))))))

(defun my/search-open (&optional replacing)
  (interactive)
  (if (and my/search-session (eq (current-buffer) (my/search-state-panel my/search-session)))
      (progn
        (when replacing (setf (my/search-state-replacing my/search-session) t)
              (my/search-build-panel my/search-session))
        (my/search-show my/search-session t)
        (goto-char (widget-field-start (if replacing (my/search-state-replace my/search-session)
                                        (my/search-state-find my/search-session)))))
    (let* ((source (current-buffer)) (window (selected-window))
           (query (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end))
                    my/search-last-query))
           (origin (point)))
      (when my/search-session (my/search-close))
      (setq my/search-session
            (make-my/search-state :source source :window window :parent (window-frame window)
                                  :panel (get-buffer-create " *Find and Replace*") :query query
                                  :replacement my/search-last-replacement :replacing replacing :origin origin))
      (my/search-build-panel my/search-session)
      (with-current-buffer source
        (add-hook 'after-change-functions #'my/search-schedule nil t)
        (add-hook 'kill-buffer-hook #'my/search-close nil t))
      (my/search-refresh my/search-session)
      (my/search-show my/search-session t))))
(defun my/search-open-replace () (interactive) (my/search-open t))

(defun my/search-close ()
  (interactive)
  (when-let* ((state my/search-session))
    (setq my/search-session nil my/search-last-query (my/search-state-query state)
          my/search-last-replacement (my/search-state-replacement state))
    (when (timerp (my/search-state-timer state)) (cancel-timer (my/search-state-timer state)))
    (my/search-clear-highlights state)
    (when (buffer-live-p (my/search-state-source state))
      (with-current-buffer (my/search-state-source state)
        (remove-hook 'after-change-functions #'my/search-schedule t)
        (remove-hook 'kill-buffer-hook #'my/search-close t)))
    (if (frame-live-p (my/search-state-popup state))
        (posframe-hide (my/search-state-panel state))
      (when-let* ((window (get-buffer-window (my/search-state-panel state) t)))
        (delete-window window)))
    (when (frame-live-p (my/search-state-parent state))
      (select-frame-set-input-focus (my/search-state-parent state)))
    (when (window-live-p (my/search-state-window state)) (select-window (my/search-state-window state)))))

(defun my/search-parent-resized (frame)
  (when (and my/search-session (eq frame (my/search-state-parent my/search-session))
             (not (equal (my/search-state-geometry my/search-session)
                         (cons (frame-pixel-width frame) (frame-pixel-height frame)))))
    (my/search-show my/search-session)))
(add-hook 'window-size-change-functions #'my/search-parent-resized)

(global-set-key (kbd "C-f") #'my/search-open)
(global-set-key (kbd "C-r") #'my/search-open-replace)
(when (boundp 'my/vscode-keys-mode-map)
  (define-key my/vscode-keys-mode-map (kbd "C-f") #'my/search-open)
  (define-key my/vscode-keys-mode-map (kbd "C-r") #'my/search-open-replace)
  (define-key my/vscode-keys-mode-map (kbd "C-h") #'my/search-open-replace))
(provide 'search-panel)
