;;; vscode-keys-tests.el --- Isolated shortcut checks -*- lexical-binding: t; -*-
(require 'ert)
;; Avoid package downloads and session restoration in these isolated tests.
(defmacro use-package (&rest _args) nil)
(dolist (file '("init.el" "vscode-keys.el"))
  (with-temp-buffer (insert-file-contents file) (emacs-lisp-mode) (check-parens)))
(load-file "vscode-keys.el")
(ert-deftest vscode-built-in-commands-exist ()
  (dolist (library '(project eglot flymake eldoc eshell dired-x tab-bar)) (require library))
  (cl-labels ((check-map (map)
               (map-keymap
                (lambda (_key command)
                  (cond ((keymapp command) (check-map command))
                        ((and (symbolp command)
                              (not (string-match-p "\\`\\(mc/\\|er/\\|consult-\\)"
                                                   (symbol-name command))))
                         (should (commandp command))))) map)))
    (check-map my/vscode-keys-mode-map)))
(ert-deftest vscode-main-bindings ()
  (with-temp-buffer
    (my/vscode-keys-mode 1)
    (dolist (binding '(("C-n" . my/vscode-new-file)
                       ("C-o" . my/vscode-open-file)
                       ("C-s" . my/vscode-save)
                       ("C-S-s" . my/vscode-save-as)
                       ("C-w" . my/vscode-close-editor)
                       ("C-x" . my/vscode-cut)
                       ("C-c" . my/vscode-copy)
                       ("C-S-l" . mc/mark-all-like-this)
                       ("C-k C-s" . my/vscode-keybindings)
                       ("<f12>" . xref-find-definitions)))
      (should (eq (key-binding (kbd (car binding))) (cdr binding))))))
(ert-deftest vscode-copy-cut-line ()
  (with-temp-buffer
    (insert "one\ntwo") (goto-char (point-min))
    (my/vscode-copy) (should (equal (current-kill 0) "one\n"))
    (my/vscode-cut) (should (equal (buffer-string) "two"))))
(ert-deftest vscode-move-lines ()
  (with-temp-buffer
    (insert "one\ntwo\nthree\n") (goto-char (point-min))
    (my/vscode-move-down)
    (should (equal (buffer-string) "two\none\nthree\n"))
    (my/vscode-move-up)
    (should (equal (buffer-string) "one\ntwo\nthree\n"))))
(ert-deftest vscode-move-last-unterminated-line ()
  (with-temp-buffer
    (insert "one\ntwo") (goto-char (point-max))
    (my/vscode-move-up)
    (should (equal (buffer-string) "two\none\n"))))
(ert-deftest vscode-duplicate-final-line ()
  (with-temp-buffer
    (insert "one") (goto-char (point-min)) (my/vscode-copy-down)
    (should (equal (buffer-string) "one\none\n"))))
(ert-deftest vscode-close-cancel-preserves-tab ()
  (let ((closed nil))
    (cl-letf (((symbol-function 'kill-buffer) (lambda (&rest _) nil))
              ((symbol-function 'tab-bar-close-tab) (lambda (&rest _) (setq closed t))))
      (my/vscode-close-editor) (should-not closed))))
(ert-deftest vscode-special-buffers-keep-keys ()
  (with-temp-buffer
    (special-mode) (my/vscode-enable-in-editor)
    (should-not my/vscode-keys-mode)))
(ert-deftest vscode-keyboard-dialog-request ()
  (let ((last-nonmenu-event ?o))
    (cl-letf (((symbol-function 'read-file-name)
               (lambda (_prompt _dir default mustmatch &rest _)
                 (should use-dialog-box)
                 (should use-file-dialog)
                 (should-not last-nonmenu-event)
                 (should (eq read-file-name-function #'read-file-name-default))
                 (should-not default)
                 (should mustmatch)
                 "chosen.txt")))
      (should (equal (my/vscode-read-file-dialog "Open: " t) "chosen.txt")))
    (should (eq last-nonmenu-event ?o))))
(ert-deftest vscode-save-untitled-uses-save-as ()
  (with-temp-buffer
    (insert "unsaved text")
    (let (called)
      (cl-letf (((symbol-function 'my/vscode-save-as) (lambda () (setq called t))))
        (my/vscode-save) (should called)))))
(ert-deftest vscode-save-existing-does-not-prompt ()
  (with-temp-buffer
    (setq buffer-file-name "existing.txt")
    (let (saved)
      (cl-letf (((symbol-function 'save-buffer) (lambda (&rest _) (setq saved t)))
                ((symbol-function 'my/vscode-save-as) (lambda () (ert-fail "Unexpected dialog"))))
        (my/vscode-save) (should saved)))))
(ert-deftest vscode-save-as-confirms-overwrite ()
  (cl-letf (((symbol-function 'my/vscode-read-file-dialog) (lambda (&rest _) "chosen.txt"))
            ((symbol-function 'write-file)
             (lambda (file confirm)
               (should (equal file "chosen.txt")) (should confirm))))
    (my/vscode-save-as)))
(ert-deftest vscode-cancel-dialog-preserves-buffer ()
  (with-temp-buffer
    (insert "keep this")
    (cl-letf (((symbol-function 'my/vscode-read-file-dialog)
               (lambda (&rest _) (signal 'quit nil))))
      (condition-case nil
          (progn (my/vscode-save-as) (ert-fail "Expected cancellation"))
        (quit nil))
      (should (equal (buffer-string) "keep this"))
      (should (buffer-modified-p))
      (should-not buffer-file-name))))
(ert-deftest vscode-save-prefills-existing-filename ()
  (with-temp-buffer
    (setq buffer-file-name (expand-file-name "folder/current name.txt" default-directory))
    (let ((system-type 'windows-nt))
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                ((symbol-function 'my/vscode-windows-save-dialog)
                 (lambda (directory filename)
                   (should (equal directory (file-name-directory buffer-file-name)))
                   (should (equal filename "current name.txt"))
                   "selected.txt")))
        (should (equal (my/vscode-read-file-dialog "Save: ") "selected.txt"))))))
(ert-deftest vscode-new-file-prefills-valid-buffer-name ()
  (with-temp-buffer
    (rename-buffer "*scratch-new*<2>" t)
    (should (equal (my/vscode-save-default-name) "scratch-new2"))))
(ert-deftest vscode-save-helper-preserves-unicode-path ()
  (cl-letf (((symbol-function 'call-process)
             (lambda (program _in _out _display &rest args)
               (should (equal program "powershell.exe"))
               (should (member "-File" args))
               (should (member "report name.txt" args))
               (insert "C:/Users/test/日本語/report name.txt")
               0)))
    (should (equal (my/vscode-windows-save-dialog default-directory "report name.txt")
                   "C:/Users/test/日本語/report name.txt"))))
(ert-deftest vscode-save-helper-cancel-does-not-return-filename ()
  (cl-letf (((symbol-function 'call-process) (lambda (&rest _) 2)))
    (condition-case nil
        (progn (my/vscode-windows-save-dialog default-directory "new.txt")
               (ert-fail "Expected quit"))
      (quit nil))))
(ert-deftest vscode-open-uses-modern-picker ()
  (let ((system-type 'windows-nt))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
              ((symbol-function 'my/vscode-windows-file-dialog)
               (lambda (directory filename mode)
                 (should (equal directory default-directory))
                 (should-not filename)
                 (should (equal mode "Open"))
                 "chosen.txt")))
      (should (equal (my/vscode-read-file-dialog "Open: " t) "chosen.txt")))))
(ert-deftest vscode-open-helper-omits-empty-filename ()
  (cl-letf (((symbol-function 'call-process)
             (lambda (_program _in _out _display &rest args)
               (should (equal (cadr (member "-Mode" args)) "Open"))
               (should-not (member "-FileName" args))
               (insert "C:/chosen.txt") 0)))
    (should (equal (my/vscode-windows-file-dialog default-directory nil "Open")
                   "C:/chosen.txt"))))
(ert-deftest vscode-other-file-dialogs-use-shared-picker ()
  (let ((system-type 'windows-nt))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
              ((symbol-function 'my/vscode-windows-file-dialog)
               (lambda (_dir filename mode)
                 (should (equal filename "current.txt"))
                 (should (equal mode "Save")) "chosen.txt")))
      (should (equal (my/vscode-modern-file-dialog
                      (lambda (&rest _) (ert-fail "Legacy file picker used"))
                      "Save: " default-directory "current.txt" nil nil)
                     "chosen.txt")))))
(ert-run-tests-batch-and-exit)
