;;; welcome-tests.el --- Welcome interactions and rendering regressions -*- lexical-binding: t; -*-
(require 'ert)
(load-file "pokemon-welcome.el")
(setq my/welcome-heading "Test welcome" kill-emacs-hook nil)

(ert-deftest welcome-buttons-preserve-command-identity ()
  (with-temp-buffer
    (setq my/welcome-width 80)
    (let ((this-command 'push-button) invoked)
      (cl-letf (((symbol-function 'execute-extended-command)
                 (lambda () (interactive)
                   (should (eq this-command 'execute-extended-command))
                   (should (eq real-this-command 'execute-extended-command))
                   (setq invoked t))))
        (my/welcome-action "Commands" 'execute-extended-command)
        (goto-char (point-min))
        (forward-button 1)
        (button-activate (button-at (point)))
        (should invoked)))))

(ert-deftest welcome-clock-is-12-hour-and-does-not-redraw-unchanged-text ()
  (with-temp-buffer
    (my/pokemon-welcome-mode)
    (my/welcome-render (selected-window))
    (cl-letf (((symbol-function 'current-time)
               (lambda () (encode-time 9 5 13 1 1 2026))))
      (my/welcome-update-clock)
      (should (equal (overlay-get my/welcome-clock 'my/last-value) "01:05:09 PM"))
      (let ((display (overlay-get my/welcome-clock 'before-string)))
        (my/welcome-update-clock)
        (should (eq display (overlay-get my/welcome-clock 'before-string)))))))

(ert-deftest welcome-reuses-animation-frames-across-layouts ()
  (with-temp-buffer
    (my/pokemon-welcome-mode)
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t)))
      (my/welcome-render (selected-window))
      (let ((images my/welcome-images))
        (should (= (length images) my/welcome-frame-count))
        (my/welcome-render (selected-window))
        (should (eq images my/welcome-images))
        (should-not (buffer-modified-p))))))

(ert-deftest welcome-hidden-screen-stops-timer ()
  (let ((my/welcome-timer (run-at-time 60 nil #'ignore)))
    (unwind-protect
        (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) nil)))
          (my/welcome-update-animation)
          (should-not my/welcome-timer))
      (when (timerp my/welcome-timer) (cancel-timer my/welcome-timer)))))

(ert-deftest welcome-all-themes-use-animated-geometry-only ()
  (dolist (theme my/welcome-themes)
    (let (previous)
      (dotimes (step my/welcome-frame-count)
        (let* ((image (funcall (plist-get (cdr theme) :art) step 480))
               (data (plist-get (cdr image) :data)))
          (should (eq (plist-get (cdr image) :type) 'svg))
          (should-not (plist-get (cdr image) :file))
          (should (string-match-p "Gradient" data))
          (should-not (string-match-p "<image\\|base64" data))
          (should-not (equal previous data))
          (setq previous data))))))

(ert-deftest welcome-tick-animates-main-scene ()
  (save-window-excursion
    (let ((buffer (get-buffer-create "*Welcome*")))
      (unwind-protect
          (progn
            (switch-to-buffer buffer)
            (my/pokemon-welcome-mode)
            (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                      ((symbol-function 'input-pending-p) (lambda () nil)))
              (my/welcome-render (selected-window))
              (let ((before (overlay-get my/welcome-art 'display)))
                (my/welcome-tick)
                (should-not (equal before (overlay-get my/welcome-art 'display))))))
        (kill-buffer buffer)
        (my/welcome-update-animation)))))

(ert-deftest welcome-themes-and-messages-rotate-between-sessions ()
  (let* ((user-emacs-directory (make-temp-file "welcome-rotation-" t))
         (file (expand-file-name "welcome-message-state" user-emacs-directory))
         (my/welcome-heading nil)
         (my/welcome-theme 'pokemon)
         (my/welcome-session-index nil)
         greetings)
    (unwind-protect
        (dotimes (session 9)
          (setq my/welcome-heading nil)
          (my/welcome-choose-message)
          (should (eq my/welcome-theme (nth (% session 3) '(pokemon beyblade bakugan))))
          (should (equal my/welcome-heading
                         (aref (my/welcome-theme-value :greetings) (/ session 3))))
          (should-not (member my/welcome-heading greetings))
          (push my/welcome-heading greetings))
      (when (file-exists-p file) (delete-file file))
      (delete-directory user-emacs-directory))))

(ert-run-tests-batch-and-exit)
